// <auto-generated />
using System;
using Examen_Chinzaruc_Alexandra_MK3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examen_Chinzaruc_Alexandra_MK3.Migrations
{
    [DbContext(typeof(Examen_Chinzaruc_Alexandra_MK3Context))]
    [Migration("20210112175208_FirstAppearanceDate")]
    partial class FirstAppearanceDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Examen_Chinzaruc_Alexandra_MK3.Models.Exhibit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comic_Universe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exhibit_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstAppearanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hero_Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Issue_of_Apparition")
                        .HasColumnType("decimal(6, 0)");

                    b.HasKey("ID");

                    b.ToTable("Exhibit");
                });
#pragma warning restore 612, 618
        }
    }
}
